# Default values for rapydbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

env: test

secretsManager:
  enabled: true
  secretName: secret-rapydbot
  serviceAccount: rapyd-secret-sa

mysql:
  user: "admin"
  password: ""
  host: "db.rapydbot.local"
  port: 3306

rapyd:
  saltLength: 8
  baseUrl: "https://sandboxapi.rapyd.net"
  accessKey: ""
  secretkey: ""

wallet:
  ipAddress: "0.0.0.0"
  port: 8080
  image: "public.ecr.aws/l0y7w6p3/rapydbot/wallet:latest"
  db_name: "WALLET"

user:
  ipAddress: "0.0.0.0"
  port: 8081
  testPort: 4102
  serverEndpoint: "/"
  image: "public.ecr.aws/l0y7w6p3/rapydbot/user:latest"
  db_name: "USER"

bot:
  token: ""
  certArn: ""
  image: "public.ecr.aws/l0y7w6p3/rapydbot/bot:latest"
  