{{- if .Values.secretsManager.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ printf "%s-%s" .Release.Name .Values.secretsManager.secretName }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secretsManager.secretName }}"
        objectType: "secretsmanager"
{{- end }}